### ISSUE TITLE
Implement Core Functionality

### ISSUE THREAD

**Issue by ShtoikoVasyl** [ShtoikoVasyl/InfrastructureService#2]
# Implement Core Functionality

This epic involves setting up the foundational microservices of the BankSimEdu project, which includes InfrastructureService, AccountService, TransactionProvider, and UserService.

## Tasks
- [ ] Set up InfrastructureService (issue #2)
- [ ] Set up AccountService (issue #3)
- [ ] Set up TransactionProvider (issue #4)
- [ ] Set up UserService (issue #5)
